=== Kika1509/dr/kms-api/src/main/resources/xsd/KmsInterface_XMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
            xmlns="http://www.kapsch.net/mcptt/xml/KmsInterface"
            targetNamespace="http://www.kapsch.net/mcptt/xml/KmsInterface" elementFormDefault="qualified" version="1.0">
    <xsd:import namespace="http://www.w3.org/2000/09/xmldsig#" schemaLocation="xmldsig-core-schema.xsd"/>

    <xsd:element type="KmsResponseType" name="KmsResponse"/>

    <xsd:complexType name="KmsResponseType">
        <xsd:sequence>
            <xsd:element type="xsd:anyURI" name="KmsUri" maxOccurs="1"/>
            <xsd:element type="xsd:anyURI" name="UserUri" maxOccurs="1"/>
            <xsd:element type="xsd:dateTime" name="Time" maxOccurs="1"/>
            <xsd:element type="xsd:string" name="KmsId" minOccurs="0" maxOccurs="1"/>
            <xsd:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element type="xsd:anyURI" name="ClientReqUrl" maxOccurs="1"/>
            <xsd:element name="KmsMessage" maxOccurs="1" minOccurs="0">
                <xsd:complexType>
                    <xsd:choice maxOccurs="1" minOccurs="0">
                        <xsd:element type="KmsInitType" name="KmsInit"/>
                        <xsd:element type="KmsKeyProvType" name="KmsKeyProv"/>
                        <xsd:element type="KmsCertCacheType" name="KmsCertCache"/>
                        <xsd:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
                    </xsd:choice>
                    <xsd:anyAttribute namespace="##other" processContents="lax"/>
                </xsd:complexType>
            </xsd:element>
            <xsd:element type="ErrorType" name="KmsError" minOccurs="0" maxOccurs="1"/>

        </xsd:sequence>
        <xsd:attribute name="Id" type="xsd:string"/>
        <xsd:attribute name="Version" type="xsd:string" fixed="1.0.0"/>
        <xsd:anyAttribute namespace="##other" processContents="lax"/>
    </xsd:complexType>

    <xsd:complexType name="ErrorType">
        <xsd:sequence>
            <xsd:element type="xsd:integer" name="ErrorCode" maxOccurs="1"/>
            <xsd:element type="xsd:string" name="ErrorMsg" maxOccurs="1"/>
            <xsd:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="Id" type="xsd:string"/>
        <xsd:attribute name="Version" type="xsd:string"/>
        <xsd:anyAttribute namespace="##other" processContents="lax"/>
    </xsd:complexType>

    <xsd:complexType name="KmsInitType">
        <xsd:sequence>
            <xsd:choice maxOccurs="1">
                <xsd:element type="SignedKmsCertificateType" name="SignedKmsCertificate"/>
                <xsd:element type="KmsCertificateType" name="KmsCertificate"/>
            </xsd:choice>
            <xsd:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="Id" type="xsd:string"/>
        <xsd:attribute name="Version" type="xsd:string"/>
        <xsd:anyAttribute namespace="##other" processContents="lax"/>
    </xsd:complexType>

    <xsd:complexType name="KmsKeyProvType">
        <xsd:sequence>
            <xsd:element type="KmsKeySetType" name="KmsKeySet" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="Id" type="xsd:string"/>
        <xsd:attribute name="Version" type="xsd:string" fixed="1.0.0"/>
        <xsd:anyAttribute namespace="##other" processContents="lax"/>
    </xsd:complexType>

    <xsd:complexType name="KmsCertCacheType">
        <xsd:sequence>
            <xsd:choice maxOccurs="unbounded" minOccurs="0">
                <xsd:element type="SignedKmsCertificateType" name="SignedKmsCertificate"/>
                <xsd:element type="KmsCertificateType" name="KmsCertificate"/>
            </xsd:choice>
            <xsd:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="Id" type="xsd:string"/>
        <xsd:attribute name="Version" type="xsd:string" fixed="1.0.0"/>
        <xsd:attribute name="CacheNum" type="xsd:integer"/>
        <xsd:anyAttribute namespace="##other" processContents="lax"/>
    </xsd:complexType>


    <xsd:element name="SignedKmsCertificate" type="SignedKmsCertificateType"/>
    <xsd:complexType name="SignedKmsCertificateType">
        <xsd:sequence>
            <xsd:element name="KmsCertificate" type="KmsCertificateType"/>
            <xsd:element ref="ds:Signature" minOccurs="0"/>
        </xsd:sequence>
        <xsd:attribute name="Id" type="xsd:string"/>
        <xsd:anyAttribute namespace="##other" processContents="lax"/>
    </xsd:complexType>

    <xsd:element name="KmsCertificate" type="KmsCertificateType"/>
    <xsd:complexType name="KmsCertificateType">
        <xsd:sequence>
            <xsd:element type="xsd:anyURI" name="KmsUri" maxOccurs="1"/>
            <xsd:element type="xsd:anyURI" name="CertUri" maxOccurs="1" minOccurs="0"/>
            <xsd:element type="xsd:string" name="Issuer" maxOccurs="1" minOccurs="0"/>
            <xsd:element type="xsd:dateTime" name="ValidFrom" maxOccurs="1" minOccurs="0"/>
            <xsd:element type="xsd:dateTime" name="ValidTo" maxOccurs="1" minOccurs="0"/>
            <xsd:element type="xsd:boolean" name="Revoked" maxOccurs="1" minOccurs="0"/>
            <xsd:element type="xsd:string" name="UserIdFormat" maxOccurs="1"/>
            <xsd:element type="xsd:integer" name="UserKeyPeriod" maxOccurs="1"/>
            <xsd:element type="xsd:integer" name="UserKeyOffset" maxOccurs="1"/>
            <xsd:element type="xsd:hexBinary" name="PubEncKey" maxOccurs="1"/>
            <xsd:element type="xsd:hexBinary" name="PubAuthKey" maxOccurs="1"/>
            <xsd:element type="xsd:integer" name="ParameterSet" maxOccurs="1" minOccurs="0"/>
            <xsd:element name="KmsDomainList" maxOccurs="1" minOccurs="0">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element type="xsd:anyURI" name="KmsDomain" maxOccurs="unbounded"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="Id" type="xsd:string"/>
        <xsd:attribute name="Version" type="xsd:string" fixed="1.1.0"/>
        <xsd:attribute name="Role" type="RoleType"/>
        <xsd:anyAttribute namespace="##other" processContents="lax"/>
    </xsd:complexType>

    <xsd:simpleType name="RoleType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Root"/>
            <xsd:enumeration value="External"/>
        </xsd:restriction>
    </xsd:simpleType>


    <xsd:element name="KmsKeySet" type="KmsKeySetType"/>

    <xsd:complexType name="KmsKeySetType">
        <xsd:sequence>
            <xsd:element type="xsd:anyURI" name="KmsUri" maxOccurs="1"/>
            <xsd:element type="xsd:anyURI" name="CertUri" maxOccurs="1" minOccurs="0"/>
            <xsd:element type="xsd:string" name="Issuer" maxOccurs="1" minOccurs="0"/>
            <xsd:element type="xsd:anyURI" name="UserUri" maxOccurs="1"/>
            <xsd:element type="xsd:string" name="UserID" maxOccurs="1"/>
            <xsd:element type="xsd:dateTime" name="ValidFrom" maxOccurs="1" minOccurs="0"/>
            <xsd:element type="xsd:dateTime" name="ValidTo" maxOccurs="1" minOccurs="0"/>
            <xsd:element type="xsd:integer" name="KeyPeriodNo" maxOccurs="1"/>
            <xsd:element type="xsd:boolean" name="Revoked" maxOccurs="1" minOccurs="0"/>
            <xsd:element type="KeyContentType" name="UserDecryptKey" maxOccurs="1"/>
            <xsd:element type="KeyContentType" name="UserSigningKeySSK" maxOccurs="1"/>
            <xsd:element type="KeyContentType" name="UserPubTokenPVT" maxOccurs="1"/>
        </xsd:sequence>
        <xsd:attribute name="Id" type="xsd:string"/>
        <xsd:attribute name="Version" type="xsd:string" fixed="1.1.0"/>
        <xsd:anyAttribute namespace="##other" processContents="lax"/>
    </xsd:complexType>

    <xsd:complexType name="KeyContentType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:hexBinary">
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

</xsd:schema>

=== Kika1509/dr/kms-api/src/test/resources/xml/KMSKeyProvExample.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<KmsResponse Version="1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			 xmlns="http://www.kapsch.net/mcptt/xml/KmsInterface"
			 xsi:schemaLocation="http://www.kapsch.net/mcptt/xml/KmsInterface KmsInterface_XMLSchema.xsd">
	<KmsUri>kms.example.org</KmsUri>
	<UserUri>test4@example.org</UserUri>
	<Time>2018-02-21T13:31:26.988</Time>
	<KmsId>kms.example.org</KmsId>
	<ClientReqUrl>/keymanagement/identity/v1/keyprov</ClientReqUrl>
	<KmsMessage>
		<KmsKeyProv Version="1.0.0">
			<KmsKeySet Version="1.1.0">
				<KmsUri>kms.example.org</KmsUri>
				<UserUri>test4@example.org</UserUri>
				<UserID>99ECDB11D33AD5CE3D69CE578F9CC0768BE812D33E31654907CE65EABBADA63C</UserID>
				<ValidFrom>2018-02-19T00:00:00</ValidFrom>
				<ValidTo>2018-03-19T00:00:00</ValidTo>
				<KeyPeriodNo>1541</KeyPeriodNo>
				<UserDecryptKey>
					04287DBDCFED0139080914158E1428CDC0BACFFD3798AD6B3423A2D4D4866DCB77B07338EB17B34E4924E72A753D7B25F9F8B86ABCB51D577B9DD776131D9B28C829C541EE24E3DA75E88EBD56D05AB28DFB5ED1C657A1C959B6C2603AA52AF48BDAB8F3ED4D11EC8EA114871DD3809A281A3AEE7B20DCBBF6E69683292A1F9AD65B86E1F56EF0743EA16A740BF717BCEC6B6D166C7B354B0F5454EF749A633ADE182FBBC757DDEE84F04379667AD0F52A834AD24E78AC4C45C377F18735C7EB504652A07A0960575CCDD066A8169EBC4DCC3DD3E8C595CB7A44E09521ADEDF6449D06D30DF03027F8FC3DC64743EEBB291905BEC5924C8559664B6E4BB43B103F
				</UserDecryptKey>
				<UserSigningKeySSK>898BE034B494065BBE4C736F6C92721BEFB078C00C48F5519E0C60739C80EF82</UserSigningKeySSK>
				<UserPubTokenPVT>
					04E685A80E5FCA4FF971EF5D0CF91E05AB94196966A0546B04E64814E4C6B16C33B49BB600D044ADCD241146C0F2A19200D483071C9F8E1491EE8515513396DF93
				</UserPubTokenPVT>
			</KmsKeySet>
		</KmsKeyProv>
	</KmsMessage>
</KmsResponse>

=== Kika1509/dr/kms-api/src/test/resources/xml/KMSKeyProvMarshallerExample.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<KmsResponse Version="1.0.0" xsi:schemaLocation="http://www.kapsch.net/mcptt/xml/KmsInterface KmsInterface_XMLSchema.xsd" xmlns="http://www.kapsch.net/mcptt/xml/KmsInterface" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<KmsUri>kms.example.org</KmsUri>
	<UserUri>user@example.org</UserUri>
	<Time>2014-01-26T10:07:14</Time>
	<KmsId>KMSProvider12345</KmsId>
	<ClientReqUrl>http://kms.example.org/keymanagement/identity/v1/keyprov</ClientReqUrl>
	<KmsMessage>
		<KmsKeyProv Version="1.0.0">
			<KmsKeySet Version="1.1.0">
				<KmsUri>kms.example.org</KmsUri>
				<CertUri>cert1.kms.example.org</CertUri>
				<Issuer>www.example.org</Issuer>
				<UserUri>user@example.org</UserUri>
				<UserID>0123456789ABCDEF0123456789ABCDEF</UserID>
				<ValidFrom>2015-12-30T00:00:00</ValidFrom>
				<ValidTo>2016-03-29T23:59:59</ValidTo>
				<KeyPeriodNo>1514</KeyPeriodNo>
				<Revoked>false</Revoked>
				<UserDecryptKey>DEADBEEF</UserDecryptKey>
				<UserSigningKeySSK>DEADBEEF</UserSigningKeySSK>
				<UserPubTokenPVT>DEADBEEF</UserPubTokenPVT>
			</KmsKeySet>
			<KmsKeySet Version="1.1.0">
				<KmsUri>kms.example.org</KmsUri>
				<CertUri>cert1.kms.example.org</CertUri>
				<Issuer>www.example.org</Issuer>
				<UserUri>user.psuedonym@example.org</UserUri>
				<UserID>0011223344556677889900AABBCCDDEEFF</UserID>
				<ValidFrom>2015-12-30T00:00:00</ValidFrom>
				<ValidTo>2016-03-29T23:59:59</ValidTo>
				<KeyPeriodNo>1514</KeyPeriodNo>
				<Revoked>false</Revoked>
				<UserDecryptKey>DEADBEEF</UserDecryptKey>
				<UserSigningKeySSK>DEADBEEF</UserSigningKeySSK>
				<UserPubTokenPVT>DEADBEEF</UserPubTokenPVT>
			</KmsKeySet>
		</KmsKeyProv>
	</KmsMessage>
</KmsResponse>

=== Kika1509/dr/kmc-api/src/test/resources/xml/KMSInitExample.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<KmsResponse Version="1.0.0" xsi:schemaLocation="http://www.kapsch.net/mcptt/xml/KmsInterface KmsInterface_XMLSchema.xsd" xmlns="http://www.kapsch.net/mcptt/xml/KmsInterface" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <KmsUri>kms.example.org</KmsUri>
    <UserUri>user@example.org</UserUri>
    <Time>2014-01-26T10:07:14</Time>
    <KmsId>KMSProvider12345</KmsId>
    <ClientReqUrl>http://kms.example.org/keymanagement/identity/v1/init</ClientReqUrl>
    <KmsMessage>
        <KmsInit Version="1.0.0">
            <KmsCertificate Version="1.1.0" Role="Root">
                <KmsUri>kms.example.org</KmsUri>
                <CertUri>cert1.kms.example.org</CertUri>
                <Issuer>www.example.org</Issuer>
                <ValidFrom>2000-01-26T00:00:00</ValidFrom>
                <ValidTo>2025-01-26T23:59:59</ValidTo>
                <Revoked>false</Revoked>
                <UserIdFormat>2</UserIdFormat>
                <UserKeyPeriod>2592000</UserKeyPeriod>
                <UserKeyOffset>0</UserKeyOffset>
                <PubEncKey>029A2F</PubEncKey>
                <PubAuthKey>029A2F</PubAuthKey>
                <ParameterSet>1</ParameterSet>
                <KmsDomainList>
                    <KmsDomain>sec1.example.org</KmsDomain>
                    <KmsDomain>sec2.example.org</KmsDomain>
                </KmsDomainList>
            </KmsCertificate>
        </KmsInit>
    </KmsMessage>
</KmsResponse>

=== Kika1509/dr/kms-api/src/test/resources/xml/KMSInitExample.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<KmsResponse Version="1.0.0" xmlns="http://www.kapsch.net/mcptt/xml/KmsInterface" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:ns3="http://www.w3.org/2001/04/xmlenc#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.kapsch.net/mcptt/xml/KmsInterface KmsInterface_XMLSchema.xsd">
	<KmsUri>kms.example.org</KmsUri>
	<UserUri>test4@example.org</UserUri>
	<Time>2018-02-26T09:57:53.627</Time>
	<KmsId>kms.example.org</KmsId>
	<ClientReqUrl>/keymanagement/identity/v1/init</ClientReqUrl>
	<KmsMessage>
		<KmsInit Version="1.0.0">
			<KmsCertificate Role="Root" Version="1.1.0">
				<KmsUri>kms.example.org</KmsUri>
				<UserIdFormat>2</UserIdFormat>
				<UserKeyPeriod>2419200</UserKeyPeriod>
				<UserKeyOffset>0</UserKeyOffset>
				<PubEncKey>044A42095E2DBEF7C804F303DDE0AB3B1449ACBAC68B9FB48DD80E777B937E01BE665F9397C3149EF0EF5FD6E902592C5C136542FAFF74475F9AB68B450549E83AFA214350DDA752D8AE8E8A96999E08B01637141B03997DAE0C7091B0D96C3DE405D58538E029997D8B616E956F412023F2E239C61068136BB07524F7D8644D0C13E4EA1349B7D3DED7C04CD25B809CF82784AC6685C9AD73CF8EA667D9794A41C1C83A37E934768D57D760D44F30EF784F216393C3E2F9AB68099BC4AA82AD29C8DA090B1AA95D493FB7C19C39F1E869C95FE0950CA53A68EE330EDFC9E055D62202CC0419282EE96C30C9B5239E832056FC112EE5CDDE811D5AF523123DE7C6</PubEncKey>
				<PubAuthKey>042CFB4C1003B36E2F7B211E9BC28CEBE2B41A0CCD4EBEA6F4EA2A4EFFD4D7144204972AECF92453255AC6E1ABEB21852F100C88EF87803F93F5A210A01000322B</PubAuthKey>
			</KmsCertificate>
		</KmsInit>
	</KmsMessage>
</KmsResponse>
